class Apartments {
  final String type,
      img,
      wifi,
      gym,
      parking,
      agency,
      location,
      offer,
      furnished,listing, payment;
  final int bedroom, kitchen, hall, bathroom, space;

  Apartments(  {
    required this.furnished,
    required this.location,
    required this.type,
    required this.img,
    required this.agency,
    required this.parking,
    required this.gym,
    required this.wifi,
    required this.space,
    required this.bathroom,
    required this.hall,
    required this.offer,
    required this.bedroom,
    required this.kitchen,
    required this.listing,
    required this.payment,
  });
}

List<Apartments> apartment = [
  Apartments(
    img: 'assets/apart 0.jpg',
    type: 'Apartment',
    listing: 'for sale',
    offer: "SDG 1,450,000",
    bathroom: 4,
    location: 'Khartoum',
    bedroom: 4,
    kitchen: 1,
    agency: 'Hasboo real estate',
    gym: 'yes',
    space: 400,
    parking: 'yes',
    hall: 3,
    furnished: 'yes',
    wifi: 'yes', payment: 'cheque',
  ),
  Apartments(
    img: 'assets/apart 1.jpg',
    type: 'Apartment',
    offer: "SDG 500,000",
    bathroom: 1,
    location: 'Khartoum',
    bedroom: 0,
    kitchen: 1,
    agency: 'Hasboo real estate',
    gym: 'no',
    space: 120,
    parking: 'yes',
    hall: 1,
    furnished: 'yes',
    wifi: 'yes', listing: 'for rent', payment: '6 month in advanced cash',
  ),
  Apartments(
    img: 'assets/apart 2.jpg',
    type: 'Apartment',
    offer: "SDG 450,000",
    bathroom: 2,
    location: 'Khartoum',
    bedroom: 1,
    kitchen: 1,
    agency: 'Hasboo real estate',
    gym: 'no',
    space: 100,
    parking: 'No',
    hall: 1,
    furnished: 'yes',
    wifi: 'yes', listing: 'For Rent', payment: 'No advance, cash or cheque',
  ),
  Apartments(
    img: 'assets/apart 3.jpg',
    type: 'Apartment',
    offer: "SDG 3,000,000",
    bathroom: 2,
    location: 'Khartoum',
    bedroom: 3,
    kitchen: 1,
    agency: 'Hasboo real estate',
    gym: 'yes',
    space: 200,
    parking: 'yes',
    hall: 3,
    furnished: 'no',
    wifi: 'no', listing: 'For Sale', payment: '50% in advance, chash or cheque',
  ),

  Apartments(
    img: 'assets/apart 4.jpg',
    type: 'Apartment',
    offer: "SDG 300,000",
    bathroom: 2,
    location: 'Portsudan',
    bedroom: 2,
    kitchen: 1,
    agency: 'Hasboo real estate',
    gym: 'no',
    space: 180,
    parking: 'No',
    hall: 1,
    furnished: 'No',
    wifi: 'yes', listing: 'For Rent', payment: 'No advance, cash or cheque',
  ),
  Apartments(
    img: 'assets/apart 5.jpg',
    type: 'Apartment',
    offer: "SDG 450,000",
    bathroom: 2,
    location: 'Khartoum',
    bedroom: 1,
    kitchen: 1,
    agency: 'Hasboo real estate',
    gym: 'no',
    space: 150,
    parking: 'No',
    hall: 1,
    furnished: 'yes',
    wifi: 'yes', listing: 'For Rent', payment: 'No advance, cash or cheque',
  ),
  Apartments(
    img: 'assets/apart 6.jpg',
    type: 'Apartment',
    offer: "SDG 200,000",
    bathroom: 1,
    location: 'Kasla',
    bedroom: 1,
    kitchen: 1,
    agency: 'Hasboo real estate',
    gym: 'no',
    space: 80,
    parking: 'No',
    hall: 1,
    furnished: 'No',
    wifi: 'No', listing: 'For Rent', payment: 'No advance, cash or cheque',
  ),
  Apartments(
    img: 'assets/apart 7.jpg',
    type: 'Apartment',
    offer: "SDG 475,000",
    bathroom: 2,
    location: 'Khartoum',
    bedroom: 1,
    kitchen: 1,
    agency: 'Hasboo real estate',
    gym: 'yes',
    space: 80,
    parking: 'No',
    hall: 1,
    furnished: 'yes',
    wifi: 'yes', listing: 'For Rent', payment: 'No advance, cash or cheque',
  ),
];
