import 'package:easy_localization/easy_localization.dart';

class Property {
  final String type,
      img,
      wifi,
      gym,
      parking,
      agency,
      location,
      offer,
      furnished,listing, payment;
  final int bedroom, kitchen, hall, bathroom, space;

  Property(  {
    required this.furnished,
    required this.location,
    required this.type,
    required this.img,
    required this.agency,
    required this.parking,
    required this.gym,
    required this.wifi,
    required this.space,
    required this.bathroom,
    required this.hall,
    required this.offer,
    required this.bedroom,
    required this.kitchen,
    required this.listing,
    required this.payment,
  });
}

List<Property> property = [

  Property(
    img: 'assets/house 0.jpg',
    type: 'house'.tr(),
    listing: 'for sale',
    offer: "SDG 1,450,000",
    bathroom: 4,
    location: 'Khartoum',
    bedroom: 4,
    kitchen: 1,
    agency: 'Hasboo real estate',
    gym: 'yes',
    space: 400,
    parking: 'yes',
    hall: 3,
    furnished: 'yes',
    wifi: 'yes', payment: 'cheque',
  ),
  Property(
    img: 'assets/house 1.jpg',
    type: 'Shop',
    offer: "SDG 500,000",
    bathroom: 1,
    location: 'Khartoum',
    bedroom: 0,
    kitchen: 1,
    agency: 'Hasboo real estate',
    gym: 'no',
    space: 120,
    parking: 'yes',
    hall: 1,
    furnished: 'yes',
    wifi: 'yes', listing: 'for rent', payment: '6 month in advanced cash',
  ),
  Property(
    img: 'assets/house 2.jpg',
    type: 'Apartment',
    offer: "SDG 450,000",
    bathroom: 2,
    location: 'Khartoum',
    bedroom: 1,
    kitchen: 1,
    agency: 'Hasboo real estate',
    gym: 'no',
    space: 100,
    parking: 'No',
    hall: 1,
    furnished: 'yes',
    wifi: 'yes', listing: 'For Rent', payment: 'No advance, cash or cheque',
  ),
  Property(
    img: 'assets/house 3.jpg',
    type: 'house'.tr(),
    offer: "SDG 3,000,000",
    bathroom: 2,
    location: 'Khartoum',
    bedroom: 3,
    kitchen: 1,
    agency: 'Hasboo real estate',
    gym: 'yes',
    space: 450,
    parking: 'yes',
    hall: 3,
    furnished: 'no',
    wifi: 'no', listing: 'For Sale', payment: '50% in advance, chash or cheque',
  ),
];
