
class Sedan {
  final String type, img, color, transmission, fuel, name, condition, offer;
  final int model, kilometer, doors, cylinders;

  Sedan({
    required this.condition,
    required this.name,
    required this.type,
    required this.img,
    required this.color,
    required this.transmission,
    required this.fuel,
    required this.model,
    required this.kilometer,
    required this.doors,
    required this.cylinders,
    required this.offer,
  });
}

List<Sedan> sedan = [
  Sedan(
      img: 'assets/sedan 0.jpg',
      type: 'Saloon',
      fuel: 'Gasoline',
      cylinders: 4,
      model: 2018,
      kilometer: 1024,
      color: 'grey',
      transmission: 'Automatic',
      offer: "SDG 4,450,000",
      doors: 4,
      name: 'Lancer',
      condition: 'Used'),
  Sedan(
      img: 'assets/sedan 1.jpg',
      type: 'Saloon',
      cylinders: 6,
      model: 2020,
      kilometer: 0,
      color: 'white',
      transmission: 'Automatic',
      offer: 'SDG 20,980,000',
      doors: 4,
      name: 'Lancer',
      condition: 'New',
      fuel: 'Gasoline'),
  Sedan(
      img: 'assets/sedan 2.jpg',
      type: 'Saloon',
      cylinders: 4,
      model: 2021,
      kilometer: 870,
      color: 'grey',
      transmission: 'Automatic',
      offer: 'SDG 10,900,000',
      doors: 4,
      name: 'chevorlett',
      condition: 'Used',
      fuel: 'Diesel'),
  Sedan(
      img: 'assets/sedan 3.jpg',
      type: 'Saloon',
      cylinders: 8,
      model: 2022,
      kilometer: 0,
      color: 'blue',
      transmission: 'Automatic',
      offer: 'SDG 30,000,000',
      doors: 4,
      name: 'Corolla',
      condition: 'New',
      fuel: 'Gasoline'),

  Sedan(
      img: 'assets/sedan 4.jpg',
      type: 'Saloon',
      cylinders: 6,
      model: 2020,
      kilometer: 0,
      color: 'white',
      transmission: 'Automatic',
      offer: 'SDG 20,980,000',
      doors: 4,
      name: 'Prado',
      condition: 'New',
      fuel: 'Gasoline'),
  Sedan(
      img: 'assets/sedan 5.jpg',
      type: 'Saloon',
      cylinders: 4,
      model: 2021,
      kilometer: 870,
      color: 'Pearl White',
      transmission: 'Automatic',
      offer: 'SDG 10,900,000',
      doors: 4,
      name: 'RAV-4',
      condition: 'Used',
      fuel: 'Diesel'),

  Sedan(
      img: 'assets/sedan 6.jpg',
      type: 'Saloon',
      fuel: 'Gasoline',
      cylinders: 4,
      model: 2018,
      kilometer: 1024,
      color: 'Black',
      transmission: 'Automatic',
      offer: "SDG 4,450,000",
      doors: 4,
      name: 'Lancer',
      condition: 'Used'),
  Sedan(
      img: 'assets/sedan 7.jpg',
      type: 'Saloon',
      cylinders: 8,
      model: 2022,
      kilometer: 0,
      color: 'White',
      transmission: 'Automatic',
      offer: 'SDG 30,000,000',
      doors: 4,
      name: 'Jeep',
      condition: 'New',
      fuel: 'Gasoline'),

];
